name: Фитнес-конвенция «Мудрость тела» 2018
url: https://mudrost-tela.ru
keywords: фитнес братск, авдонина, мудрость тела, фитнес-конвенция, фитнес конвенция, fitness-конвенция
description: 6-ая фитнес-конвенция «Мудрость тела» - ежегодный форум массовой физкультуры и спорта

analytics:
	yandex:
		tracking_code: 40594255